// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA52T6SavHpR0tFbiwGzoUhHVJ9hbu4AS0',
    appId: '1:370161803855:web:a0050b3fa76b05ee74c03a',
    messagingSenderId: '370161803855',
    projectId: 'flutter-log-in-54d30',
    authDomain: 'flutter-log-in-54d30.firebaseapp.com',
    storageBucket: 'flutter-log-in-54d30.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmbOzijrJ2aBSddq9s-VH-0aNCqrglCVk',
    appId: '1:370161803855:android:6d20f07c80b9205574c03a',
    messagingSenderId: '370161803855',
    projectId: 'flutter-log-in-54d30',
    storageBucket: 'flutter-log-in-54d30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVgcRUdz7cFx8WFs2g86C5c8jL8yLXlCc',
    appId: '1:370161803855:ios:fb478ba39c237d9574c03a',
    messagingSenderId: '370161803855',
    projectId: 'flutter-log-in-54d30',
    storageBucket: 'flutter-log-in-54d30.appspot.com',
    iosClientId: '370161803855-ehggdeor5jfon1pruj42ko1psshjk55k.apps.googleusercontent.com',
    iosBundleId: 'com.example.testV3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVgcRUdz7cFx8WFs2g86C5c8jL8yLXlCc',
    appId: '1:370161803855:ios:fb478ba39c237d9574c03a',
    messagingSenderId: '370161803855',
    projectId: 'flutter-log-in-54d30',
    storageBucket: 'flutter-log-in-54d30.appspot.com',
    iosClientId: '370161803855-ehggdeor5jfon1pruj42ko1psshjk55k.apps.googleusercontent.com',
    iosBundleId: 'com.example.testV3',
  );
}
